---
- hosts: all
  sudo: yes
  vars_files:
    - vars/external_vars.yml

  roles:
    - influxdb
    - cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: enter_your_secure_password
    # - grafana
    # - nginx
    # - python-server-metrics